default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --all
        language: system
        pass_filenames: false
        always_run: true
      - id: clippy
        name: clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        always_run: true
      - id: openapi-generate
        name: openapi-generate
        entry: bash -c 'make openapi && git add docs/openapi.yaml'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
